/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.employment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobListing service. Represents a row in the &quot;Employment_JobListing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.employment.model.impl.JobListingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.employment.model.impl.JobListingImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see JobListing
 * @see com.liferay.portlet.employment.model.impl.JobListingImpl
 * @see com.liferay.portlet.employment.model.impl.JobListingModelImpl
 * @generated
 */
public interface JobListingModel extends BaseModel<JobListing>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job listing model instance should use the {@link JobListing} interface instead.
	 */

	/**
	 * Gets the primary key of this job listing.
	 *
	 * @return the primary key of this job listing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job listing
	 *
	 * @param primaryKey the primary key of this job listing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Gets the job listing ID of this job listing.
	 *
	 * @return the job listing ID of this job listing
	 */
	public long getJobListingId();

	/**
	 * Sets the job listing ID of this job listing.
	 *
	 * @param jobListingId the job listing ID of this job listing
	 */
	public void setJobListingId(long jobListingId);

	/**
	 * Gets the group ID of this job listing.
	 *
	 * @return the group ID of this job listing
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this job listing.
	 *
	 * @param groupId the group ID of this job listing
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company ID of this job listing.
	 *
	 * @return the company ID of this job listing
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job listing.
	 *
	 * @param companyId the company ID of this job listing
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user ID of this job listing.
	 *
	 * @return the user ID of this job listing
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job listing.
	 *
	 * @param userId the user ID of this job listing
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this job listing.
	 *
	 * @return the user uuid of this job listing
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job listing.
	 *
	 * @param userUuid the user uuid of this job listing
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this job listing.
	 *
	 * @return the user name of this job listing
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this job listing.
	 *
	 * @param userName the user name of this job listing
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this job listing.
	 *
	 * @return the create date of this job listing
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this job listing.
	 *
	 * @param createDate the create date of this job listing
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this job listing.
	 *
	 * @return the modified date of this job listing
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job listing.
	 *
	 * @param modifiedDate the modified date of this job listing
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the title of this job listing.
	 *
	 * @return the title of this job listing
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this job listing.
	 *
	 * @param title the title of this job listing
	 */
	public void setTitle(String title);

	/**
	 * Gets the description of this job listing.
	 *
	 * @return the description of this job listing
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this job listing.
	 *
	 * @param description the description of this job listing
	 */
	public void setDescription(String description);

	/**
	 * Gets the email address of this job listing.
	 *
	 * @return the email address of this job listing
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this job listing.
	 *
	 * @param emailAddress the email address of this job listing
	 */
	public void setEmailAddress(String emailAddress);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(JobListing jobListing);

	public int hashCode();

	public CacheModel<JobListing> toCacheModel();

	public JobListing toEscapedModel();

	public String toString();

	public String toXmlString();
}