/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.employment.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.employment.model.JobListing;
import com.liferay.portlet.employment.service.JobListingLocalService;
import com.liferay.portlet.employment.service.persistence.JobListingPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the job listing local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.employment.service.impl.JobListingLocalServiceImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see com.liferay.portlet.employment.service.impl.JobListingLocalServiceImpl
 * @see com.liferay.portlet.employment.service.JobListingLocalServiceUtil
 * @generated
 */
public abstract class JobListingLocalServiceBaseImpl
	implements JobListingLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.portlet.employment.service.JobListingLocalServiceUtil} to access the job listing local service.
	 */

	/**
	 * Adds the job listing to the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobListing the job listing
	 * @return the job listing that was added
	 * @throws SystemException if a system exception occurred
	 */
	public JobListing addJobListing(JobListing jobListing)
		throws SystemException {
		jobListing.setNew(true);

		jobListing = jobListingPersistence.update(jobListing, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(jobListing);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return jobListing;
	}

	/**
	 * Creates a new job listing with the primary key. Does not add the job listing to the database.
	 *
	 * @param jobListingId the primary key for the new job listing
	 * @return the new job listing
	 */
	public JobListing createJobListing(long jobListingId) {
		return jobListingPersistence.create(jobListingId);
	}

	/**
	 * Deletes the job listing with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobListingId the primary key of the job listing
	 * @throws PortalException if a job listing with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteJobListing(long jobListingId)
		throws PortalException, SystemException {
		JobListing jobListing = jobListingPersistence.remove(jobListingId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(jobListing);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the job listing from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobListing the job listing
	 * @throws PortalException
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteJobListing(JobListing jobListing)
		throws PortalException, SystemException {
		jobListingPersistence.remove(jobListing);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(jobListing);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return jobListingPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return jobListingPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return jobListingPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return jobListingPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the job listing with the primary key.
	 *
	 * @param jobListingId the primary key of the job listing
	 * @return the job listing
	 * @throws PortalException if a job listing with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public JobListing getJobListing(long jobListingId)
		throws PortalException, SystemException {
		return jobListingPersistence.findByPrimaryKey(jobListingId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return jobListingPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the job listings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of job listings
	 * @param end the upper bound of the range of job listings (not inclusive)
	 * @return the range of job listings
	 * @throws SystemException if a system exception occurred
	 */
	public List<JobListing> getJobListings(int start, int end)
		throws SystemException {
		return jobListingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of job listings.
	 *
	 * @return the number of job listings
	 * @throws SystemException if a system exception occurred
	 */
	public int getJobListingsCount() throws SystemException {
		return jobListingPersistence.countAll();
	}

	/**
	 * Updates the job listing in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param jobListing the job listing
	 * @return the job listing that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public JobListing updateJobListing(JobListing jobListing)
		throws SystemException {
		return updateJobListing(jobListing, true);
	}

	/**
	 * Updates the job listing in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param jobListing the job listing
	 * @param merge whether to merge the job listing with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the job listing that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public JobListing updateJobListing(JobListing jobListing, boolean merge)
		throws SystemException {
		jobListing.setNew(false);

		jobListing = jobListingPersistence.update(jobListing, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(jobListing);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return jobListing;
	}

	/**
	 * Returns the job listing local service.
	 *
	 * @return the job listing local service
	 */
	public JobListingLocalService getJobListingLocalService() {
		return jobListingLocalService;
	}

	/**
	 * Sets the job listing local service.
	 *
	 * @param jobListingLocalService the job listing local service
	 */
	public void setJobListingLocalService(
		JobListingLocalService jobListingLocalService) {
		this.jobListingLocalService = jobListingLocalService;
	}

	/**
	 * Returns the job listing persistence.
	 *
	 * @return the job listing persistence
	 */
	public JobListingPersistence getJobListingPersistence() {
		return jobListingPersistence;
	}

	/**
	 * Sets the job listing persistence.
	 *
	 * @param jobListingPersistence the job listing persistence
	 */
	public void setJobListingPersistence(
		JobListingPersistence jobListingPersistence) {
		this.jobListingPersistence = jobListingPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.liferay.portlet.employment.model.JobListing",
			jobListingLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.portlet.employment.model.JobListing");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return JobListing.class;
	}

	protected String getModelClassName() {
		return JobListing.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = jobListingPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = JobListingLocalService.class)
	protected JobListingLocalService jobListingLocalService;
	@BeanReference(type = JobListingPersistence.class)
	protected JobListingPersistence jobListingPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(JobListingLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}